AWSTemplateFormatVersion '2010-09-09'
Transform AWSServerless-2016-10-31
Description 
  lambda-micronaut-sample
  Sample SAM Template for lambda-micronaut

Globals
  Function
    Tracing Active
    CodeUri buildlibsHandsOnOne2-0.1-all.jar
    Runtime java17
    Timeout 30
    MemorySize 1024

Resources
  MyApi
    Type AWSServerlessApi
    Properties
      StageName prod
      Name SM703 Hands-on-prod


  HelloWorldFunctionProd
    Type AWSServerlessFunction
    Properties
      Handler io.micronaut.function.aws.proxy.MicronautLambdaHandler
      Policies
      Events
        GetHelloWorld
          Type Api
          Properties
            RestApiId !Ref MyApi
            Path 
            Method get

  HelloWorldFunctionLogGroupProd
    Type AWSLogsLogGroup
    Properties
      LogGroupName !Sub awslambda${HelloWorldFunctionProd}
      RetentionInDays 7

Outputs
  MicronautApiEndpoint
    Description API Gateway endpoint URL for Prod stage for Micronaut sample function
    Value !Sub https${MyApi}.execute-api.${AWSRegion}.amazonaws.comprod