AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-micronaut-sample
  Sample SAM Template for lambda-micronaut

Globals:
  Function:
    Tracing: Active
    CodeUri: build/libs/HandsOnOne-0.1-all.jar
    Runtime: java17
    Timeout: 30
    MemorySize: 1024

Resources:
  MyApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: qa
      Name: SM703 Hands-on-qa


  HelloWorldFunctionQA:
    Type: AWS::Serverless::Function
    Properties:
      Handler: io.micronaut.function.aws.proxy.MicronautLambdaHandler
      Policies:
      Events:
        GetHelloWorld:
          Type: Api
          Properties:
            RestApiId: !Ref MyApi
            Path: /
            Method: get

  HelloWorldFunctionLogGroupQA:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${HelloWorldFunctionQA}"
      RetentionInDays: 7

Outputs:
  MicronautApiEndpoint:
    Description: "API Gateway endpoint URL for QA stage for Micronaut sample function"
    Value: !Sub "https://${MyApi}.execute-api.${AWS::Region}.amazonaws.com/qa/"